<?php


include_once 'inc/education_common.properties.inc';
include_once 'inc/education_common.emails.inc';


/**
 * Implements hook_theme()
 */
function education_common_theme() {
  return array(
    'education_common_mail_body' => array(
      'variables' => array(
        'order_items' => NULL,
        'order_num' => NULL,
        'order_uid' => NULL,
        'order_total' => NULL,
        //'order_delivery'=> NULL,
        //'order_payment'=> NULL,
        //'order_comment'=> NULL,
      ),
      'path' => drupal_get_path('module', 'education_common') . '/templates',
      'template' => 'education-common-mail-body',
    ),
  );
}


/**
 * Implementation of hook_rules_event_info()
 */
function education_common_rules_event_info() {
  return array(
    'education_common_send_message_to_user' => array(
      'label' => t('Send message to user'),
      'module' => 'education_common',
      'group' => 'Booking a lesson' ,
      'variables' => array(
        'email' => array('type' => 'text', 'label' => t('User email form quick order form')),
        'name' => array('type' => 'text', 'label' => t('User name')),
        'phone' => array('type' => 'text', 'label' => t('User phone')),
        'skype' => array('type' => 'text', 'label' => t('Skype login')),
        'order_id' => array('type' => 'text', 'label' => t('Order Id')),
        'order_mail_data' => array('type' => 'text', 'label' => t('Order mail data')),
        //'order_mail_data_admin' => array('type' => 'text', 'label' => t('Order mail data admin')),
        //'order_type_title' => array('type' => 'text', 'label' => t('Order typ title')),
      ),
    ),

    'education_common_send_new_user_account_data' => array(
      'label' => t('Send new user account data'),
      'module' => 'education_common',
      'group' => 'Booking a lesson' ,
      'variables' => array(
        'email' => array('type' => 'text', 'label' => t('User email form quick order form')),
        'name' => array('type' => 'text', 'label' => t('User name')),
        'phone' => array('type' => 'text', 'label' => t('User phone')),
        'one_time_login' => array('type' => 'text', 'label' => t('User one time login url')),
      ),
    ),

  );
}

function education_common_preprocess_views_view(&$vars) {
  $name = $vars['view']->name;
  if ($name == 'lesson_calendar') {
    foreach ($vars['view']->result as $res_item) {
      //$res_item->field_data_field_lesson_date_field_lesson_date_value
    }
  }
}

/**
 * Implements hook_form_alter
 */
function education_common_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {

  if ($form['#id'] == 'views-exposed-form-teachers-index-page') {
    ///////////////////////////////////////////////////
    $form['submit']['#weight'] = 30;

    //unset($form['teacher_lessons_dates']);
    /*
    $field_grade_subject_options = $form['field_grade_subject']['#options'];
    $field_grade_subject_options_new = array();
    foreach ($field_grade_subject_options as $option) {
      if (!strstr($option, 'Grade')) {
        $field_grade_subject_options_new[] = $option;
      }
    }
    $form['field_grade_subject']['#options'] = $field_grade_subject_options_new;
    */

    $form['teacher_lessons_dates']['#access'] = FALSE;

    $form['teacher_date_dates'] = array (
      '#type' => 'date_popup',
      '#size' => 30,
      '#default_value' => date('Y-m-d', time()),
      '#date_format' => 'Y-m-d',
      '#date_year_range' => '-3:+3',
      '#description' => '',
    );

    $form['time_slider'] = array(
      '#title' => 'Select time range',
      '#input_title' => NULL,
      '#input2_title' => NULL,
      '#type' => 'slider',
      '#default_value' => array('value' => 0.00, 'value2' => 24.00),
      //'#orientation' => 'vertical',
     // '#slider_style' => 'orange',
      '#range' => TRUE,
      '#min' => 0.00,
      '#max' => 24.00,
      '#step' => 1.00,
     // '#display_bubble' => TRUE,
      //'#display_bubble_format' => '$%{value}%MIN||$%{value}%MAX',
      //'#required' => 1,
      //'#disabled' => TRUE,
      '#display_inputs' => FALSE,
      '#display_values' => TRUE,
      '#display_values_format' => '%{value}%.00',
      '#weight' => 29,
    );
    ///////////////////////////////////////////////////
  }

}

/**
 * hook_search_api_query_alter
 */
function education_common_search_api_query_alter(SearchApiQueryInterface $query) {
  if ($query->getOption('search id') == 'search_api_views:teachers_index:page') {
    if (isset($_GET['time_slider'])) {

      //echo '<pre>'; print_r($_GET['time_slider']); echo '</pre>';  die();
      $time_slider_arr = $_GET['time_slider'];
      $time_slider_from = $_GET['time_slider']['value'];
      $time_slider_to = $_GET['time_slider']['value2'];

      $teacher_lesson_date = strtotime($_GET['teacher_date_dates']['date']);
      //$t_d = date('Y-m-d H:i', $teacher_lesson_date);

      $right_filter = $query->createFilter('AND');

      $time_min = $teacher_lesson_date + $time_slider_from * 3600;
      $time_max = $teacher_lesson_date + $time_slider_to * 3600;

      //$t_d_min = date('Y-m-d H:i', $time_min);
      //$t_d_max = date('Y-m-d H:i', $time_max);

      $right_filter->condition('teacher_lessons_dates', $time_min, '>=');
      $right_filter->condition('teacher_lessons_dates', $time_max, '<=');

      $main_filter = $query->createFilter('AND');
      $main_filter->filter($right_filter);
      $query->filter($main_filter);
    }

  }

}

function education_common_set_query_filter_ad(&$query) {
  /*
  $pg_num = preg_replace('~[^0-9]+~', '', arg(1));

  //set range of rated power valuee ( -10% - +30%)
  $pg_num_min = $pg_num - $pg_num * 0.1;
  $pg_num_max = $pg_num + $pg_num * 0.3;

  $right_filter = $query->createFilter('AND');
  $right_filter->condition('field_rated_power:field_watts', $pg_num_min . ' кВт', '>=');
  $right_filter->condition('field_rated_power:field_watts', $pg_num_max . ' кВт', '<=');

  // for all but 1000-kvt
  if (arg(1) != 'ad-1000') {
    // condition field_engine:field_manufacturer
    $man_filter = $query->createFilter('OR');
    $man_tids = array(166, 61, 63, 55, 58);

    foreach ($man_tids as $tid) {
      $man_filter->condition('field_engine:field_manufacturer', $tid, '=');
    }
  }

  $main_filter = $query->createFilter('AND');
  $main_filter->filter($right_filter);

  //filter all but 1000-kvt
  if (arg(1) != 'ad-1000') {
    $main_filter->filter($man_filter);
  }

  $query->filter($main_filter);
  */

}


function education_common_preprocess_user_profile(&$variables) {
  //unset($variables['elements']['user_picture']);
  //unset($variables['user_profile']);
}

/**
 * Helper to rendered block().
 */
function education_common_get_rendered_block($module_name, $block_name) {
  $block_render_data = block_load($module_name, $block_name);
  $block_render_data = _block_render_blocks(array($block_render_data));
  $block_build = _block_get_renderable_array($block_render_data);
  $rendered_block = drupal_render($block_build);
  return $rendered_block;
}

/**
 * Override or insert variables into the node template.
 */
function education_common_preprocess_page(&$variables) {
  if (strstr(current_path(), 'user/') && !strstr(current_path(), 'admin/') ) {
    $block_quick_order = education_common_get_rendered_block('education_common', 'form-quick-order');
    $variables['quick_order_form'] = $block_quick_order;
    drupal_add_js(drupal_get_path('module', 'education_common') . '/js/book.js');
  }
}

/**
 * Implements hook_block_info
 */
function education_common_block_info() {
  $blocks['form-quick-order'] = array(
    'info' => 'Booking form',
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function education_common_block_view($delta = '') {
  $block = array(
    'subject' => '',
    'content' => '',
  );

  switch ($delta) {
    case 'form-quick-order':
      $block['subject'] = t('Book a lesson');
      $block['content'] = drupal_get_form('education_common_quick_order');
      break;
  }
  return $block;
}


/**
 * Quick order form
 */
function education_common_quick_order($form, &$form_state) {
  global $user;
  //if ($user->uid) {
  $user_profile = user_load($user->uid);
  //}
  $form['info'] = array(
    '#type' => 'markup',
    '#markup' => '<div class="form__desc">For quick booking fill the form.<br /> Our manager will get in touch with you.<br /></div>',
    '#theme_wrappers' => array(),
    '#prefix' => '<div class="form__block">',
    '#suffix' => '</div>',
  );

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => 'Your name',
    '#attributes' => array(
      'placeholder' => 'Your name',
    ),
    //'#theme_wrappers' => array(),
    '#default_value' => isset($user_profile->name) ? $user_profile->name :  '',
    '#required' => TRUE,
    '#prefix' => '<div class="form__block">',
    '#suffix' => '</div>',
  );

  $form['user_phone'] = array(
    '#type' => 'textfield',
    '#title' => 'Phone',
    '#attributes' => array(
      'placeholder' => t('Phone'),
    ),
    //'#theme_wrappers' => array(),
    '#default_value' =>  isset($user_profile->field_phone['und']) ? $user_profile->field_phone['und'][0]['value'] :  '',
    '#required' => TRUE,
    '#prefix' => '<div class="form__block">',
    '#suffix' => '</div>',
  );

  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => 'E-mail',
    '#attributes' => array(
      'placeholder' => 'E-mail',
    ),
    //'#theme_wrappers' => array(),
    '#default_value' => isset($user_profile->mail) ? $user_profile->mail :  '',
    '#required' => TRUE,
    '#prefix' => '<div class="form__block">',
    '#suffix' => '</div>',
  );

  $form['current_path'] = array(
    '#type' => 'hidden',
    '#default_value' => current_path(),
  );

  $form['product_id'] = array(
    '#type' => 'hidden',
    '#default_value' =>'',
  );

  $form['teacher_uid'] = array(
    '#type' => 'hidden',
    '#default_value' =>'',
  );

  $form['lesson_date'] = array(
    /*
    '#type' => 'hidden',
    '#default_value' =>'',
    */
    '#type' => 'textfield',
    '#title' => 'Lesson date',
    '#attributes' => array(
      'placeholder' => t('Lesson date'),
    ),
    //'#theme_wrappers' => array(),
    '#default_value' =>  isset($user_profile->field_phone['und']) ? $user_profile->field_phone['und'][0]['value'] :  '',
    '#required' => TRUE,
    '#prefix' => '<div class="form__block">',
    '#suffix' => '</div>',
  );

  $form['skype'] = array(
    '#type' => 'textfield',
    '#title' => 'Skype login',
    '#attributes' => array(
      'placeholder' => t('Skype login'),
    ),
    //'#theme_wrappers' => array(),
    '#default_value' =>  isset($user_profile->field_skype['und']) ? $user_profile->field_skype['und'][0]['value'] :  '',
    '#required' => TRUE,
    '#prefix' => '<div class="form__block">',
    '#suffix' => '</div>',
  );

  $form['product_quantity'] = array(
    '#type' => 'hidden',
    '#default_value' =>'1',
  );

  /*
  $form['is_cart'] = array(
    '#type' => 'hidden',
    '#default_value' => current_path() == 'cart' ? '1' : '0',
  );
  */

  /*
  $form['terms_of_use'] = array(
    '#theme_wrappers' => array(),
    '#type' => 'checkbox',
    '#title' => 'Terms of use agree.',
    '#required' => TRUE,
    '#suffix' => '<a class="term_of_use" href="/terms-of-use">Learn more</a>',
  );
  */

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Book'),
    '#attributes' => array(
      'class' => array(
        'btn btn_red form__submit',
      ),
    ),
    '#prefix' => '<div class="form__block">',
    '#suffix' => '</div>',
    '#ajax' => array(
      'callback' => 'education_common_quick_order_ajax_callback',
    ),
  );

  //honeypot_add_form_protection($form, $form_state, array('honeypot', 'time_restriction'));
  return $form;
}


function education_common_quick_order_submit(&$form, &$form_state) {
  global $user;

  $product_id = $form_state['values']['product_id'];

  if ($form_state['values']['product_quantity']) {
    if ($product_id) {
      $teacher_uid = $form_state['values']['teacher_uid'];
      $date = $form_state['values']['lesson_date'];

      $order_id = education_common_create_quick_order($user, $product_id, $form_state['values']['product_quantity'], $date, $teacher_uid,
        $form_state['values']['user_phone'], $form_state['values']['name'], $form_state['values']['email'], $form_state['values']['skype'], $form_state['values']['is_cart']);

      $form_state['values']['order_id'] = $order_id;

      $order = commerce_order_load($order_id);
      //$order_mail_data = education_common_get_order_mail_data($order);
      //$order_mail_data_admin = education_common_get_order_mail_data_admin($order);

      $order_user = user_load($order->uid);
      // получим тип заказа
      if ($order_user && in_array(2, array_keys($order_user->roles))) {
        $order_type_title = 'заказ';
      }

      if ($order_user && in_array(5, array_keys($order_user->roles))) {
        $order_type_title = 'оптовый заказ';
      }

      $order_mail_data = education_common_get_order_mail_data($order);

      /*
      rules_invoke_event('education_common_send_message_to_user', $form_state['values']['email'], $form_state['values']['name'],
        $form_state['values']['user_phone'], $order_id, $order_mail_data, $order_mail_data_admin, $order_type_title);
      */

      rules_invoke_event('education_common_send_message_to_user', $form_state['values']['email'], $form_state['values']['name'],
        $form_state['values']['user_phone'], $form_state['values']['skype'], $order_id, $order_mail_data);

    }
  }
}


function education_common_quick_order_ajax_callback(&$form, &$form_state) {
  $current_path = '';
  $current_path_text = '';

  if (form_get_errors()) {
    $commands[] = ajax_command_html('#' . $form['#id'], render($form));
    $errors = form_get_errors();
    if (isset($errors['name'])) {

      if ($errors['name'] == 'user_mail_exists') {
        $commands[] = ajax_command_after('#fast_cart input[name="name"]', '<div class="field__error">This value is in use</div>');
      }
      else {
        $commands[] = ajax_command_after('#fast_cart input[name="name"]', '<div class="field__error">Field "Name" is required</div>');
      }
    }

    if (isset($errors['user_phone'])) {
      $commands[] = ajax_command_after('#fast_cart input[name="user_phone"]', '<div class="field__error">Field "Phone" is required</div>');
    }

    if (isset($errors['email'])) {

      $email_error_text = $errors['email'] == 'email_error' ? 'E-mail address is not corrent' : 'Field "E-mail" is required';

      if ($errors['email'] == 'user_mail_exists') {
        $email_error_text = 'This value is in use';
      }

      $commands[] = ajax_command_after('#fast_cart input[name="email"]', '<div class="field__error">' . $email_error_text . '</div>');
    }

    if (isset($errors['terms_of_use'])) {
      $commands[] = ajax_command_after('#fast_cart .term_of_use', '<div class="field__error terms">Must be your agreement</div>');
    }
  }

  else {
    if ($form_state['values']['is_cart']) {
      $commands[] = array('command' => 'reloadPage');
    }

    if ($form_state['values']['current_path']) {
      $current_path_text = 'Return to page';
      $current_path = $form_state['values']['current_path'];

      if ( strstr($current_path, 'products') || strstr($current_path, 'cart') ) {
        $current_path_text = 'Return to page';
      }
    }

    $message = "<p>";
    $path_to_return = l($current_path_text, $current_path);

    if (isset($form_state['values']['is_cr'])) {

    }

    else {
      $message .= '<div class="form__block"><div class="form__desc">Thanks for booking!<br />
    Details of the booking were send to email.<br />
        Our manager will get in touch with you soon<br /><br />' . $path_to_return . '</div></div>';
    }

    $message .= "</p>";
    $commands[] = ajax_command_replace('#' . $form['#id'], $message);
  }

  return array('#type' => 'ajax', '#commands' => $commands);

}


/**
 * Создание пользователя во время создания "быстрого заказа"
 */
function education_common_create_quick_order_user($name, $pass, $mail, $phone, $skype) {

  //$roles =  array(DRUPAL_AUTHENTICATED_RID => TRUE);
  $roles =  array(DRUPAL_AUTHENTICATED_RID => 'authenticated user',
    5 => 'Student',); //

  $new_user = user_save(NULL, array(
    //'name' => $mail,
    'name' => $name,
    //'pass' => $pass,
    'mail' => $mail,
    'init' => 'email address',
    'status' => 1,
    'roles' => $roles,  //

    'field_phone' => array(
      'und' => array(
        0 => array(
          'value' => $phone,
        )
      )
    ),

    'field_skype' => array(
      'und' => array(
        0 => array(
          'value' => $skype,
        )
      )
    ),

    /*
    'field_discount' => array(
      'und' => array(
        0 => array(
          'value' => 0,
        )
      )
    ),
    */

    /*
    'field_user_guid' => array(
      'und' => array(
        0 => array(
          'value' => $guid,
        )
      )
    ),
    */

    /*
    'field_user_fio' => array(
      'und' => array(
        0 => array(
          'value' => $name,
        )
      )
    ),
    */

    /*
    'field_terms_of_use' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        )
      )
    ),
    */

  ));

  $one_time_login_url = user_pass_reset_url($new_user);
  rules_invoke_event('education_common_send_new_user_account_data', $mail, $name,
    $phone, $one_time_login_url);

  return $new_user;
}

/**
 * Создание "быстрого заказа"
 */
function education_common_create_quick_order($user, $product_id, $quantity=1, $date, $teacher_uid,  $user_phone, $name, $email, $skype, $is_cart) {

  global $user;

  //$user_phone = hb_user_clear_phone($user_phone);
  // for anonymous
  if (!$user->uid) {
    // TODO check by email
    $user_account = user_load_by_mail($email);
    if ($user_account) {
      $new_user = $user_account;
    }
    else {
      $new_user = education_common_create_quick_order_user($name, 0, $email, $user_phone, $skype);
    }
  }

  //$new_user = TRUE;
  // Create order
  if ($new_user) {
    $order = commerce_order_new($new_user->uid, 'pending');
  }
  else {
    $order = commerce_order_new($user->uid, 'pending');
  }
  commerce_order_save($order);

  // Create order line item
  $product = commerce_product_load($product_id);
  $line_item = commerce_product_line_item_new($product, $quantity, $order->order_id);
  commerce_line_item_save($line_item);

  // Attach line item to order
  $order->commerce_line_items['und'][] = (array)$line_item;
  // TODO - для order NEED to ADD fields lesson_date и teacher
  $order->field_order_lesson_date['und'][0]['value'] = $date;
  $order->field_lesson_teacher_uid['und'][0]['uid'] = $teacher_uid;
  $order->field_skype['und'][0]['value'] = $skype;

  /*
  $profile_wrapper = entity_metadata_wrapper('commerce_customer_profile', $profile);

  $profile_wrapper->commerce_customer_address->name_line = $name;
  $profile_wrapper->commerce_customer_address->phone_number = $user_phone;

  // $profile_wrapper->field_phone = $user_phone;
//  $profile_wrapper->field_email = $email;
  $profile_wrapper->save();

  $order->commerce_customer_shipping[LANGUAGE_NONE][0]['profile_id'] = $profile->profile_id;
  */
  commerce_order_save($order);

  if ($user_phone) {
    // sms о заказе
    // $msg = 'Booking  № ' . $order->order_id . ' is created';
    //  education_common_send_sms($order, $msg, $user_phone);
  }

  return $order->order_id;
}

