<?php

//define('STUDENT_ROLE', 5);

/**
 * Implements hook_theme()
 */
function education_pupil_theme() {
  return array(
    'education_pupil_pupil_menu' => array(
      'variables' => array(
        'menu_items' => NULL,
      ),
      'path' => drupal_get_path('module', 'education_pupil') . '/templates',
      'template' => 'education-pupil-pupil-menu',
    ),
  );

}

/**
 * Override or insert variables into the node template.
 */
function education_pupil_preprocess_page(&$variables) {
  global $user;
  //$variables['show_user_menu'] = FALSE;
  $variables['show_user_menu'] = FALSE;
  if (user_has_role(STUDENT_ROLE)) {
    $variables['show_user_menu']= TRUE;
  }

  $pupils_menu = menu_tree('menu-pupils-menu');

  $menu_items = array();
  foreach ($pupils_menu as $key => $pupils_menu_item) {
    if (is_numeric($key)) {
      $menu_items[] = array(
        'href' => $pupils_menu_item['#href'] == '<front>' ? '/' : $pupils_menu_item['#href'],
        'title' =>  $pupils_menu_item['#title'],
      );
    }
  }

  $variables['education_pupil_pupil_menu'] = theme('education_pupil_pupil_menu', array('menu_items' => $menu_items));
}


/**
 * Implements hook_block_info
 */
function education_pupil_block_info() {
  $blocks['student-balance'] = array(
    'info' => 'Student Balance',
  );

  return $blocks;
}

/**
 * Implements hook_block_view
 */
function education_pupil_block_view($delta = '') {
  $block = array(
    'subject' => '',
    'content' => '',
  );

  switch ($delta) {
    case 'student-balance':
      $block['subject'] = t('');

      global $user;
      $account = user_load($user->uid);
      $summ = isset($account->field_balance[LANGUAGE_NONE]) ? $account->field_balance[LANGUAGE_NONE][0]['value'] : 0;
      //$balance_summ = $summ;

      $block['content']['#markup'] = '<div class="balance"><div class="user-balance">Your balance is: ' . $summ . 'С$</div></div>';
      break;
  }
  return $block;
}
